version: '3.8'

services:
  nodejs-starter:
    image: nodejs-starter:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
